name: evio_fan
description: Evio Club - App para fans
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  evio_core:
    path: ../../packages/evio_core
  flutter_riverpod: ^2.6.1
  state_notifier: ^1.0.0
  go_router: ^17.0.0  
  intl: ^0.19.0
  supabase_flutter: ^2.8.0
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.9
  screen_brightness: ^1.0.1
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.0
  youtube_player_flutter: ^8.1.2
  shimmer: ^3.0.0
  riverpod_annotation: ^2.6.1
  geolocator: ^13.0.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^2.6.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/