name: evio_admin
description: Evio Club - Panel de administracion
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  evio_core:
    path: ../../packages/evio_core
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.0
  go_router: ^17.0.0
  intl: ^0.19.0
  uuid: ^4.0.0
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.9
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
